export const CREATE_ENTRY = 'CREATE_ENTRY';
export const CREATE_ENTRY_ERROR = 'CREATE_ENTRY_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
