export const CREATE_ENTRY = 'CREATE_ENTRY';
export const CREATE_ENTRY_ERROR = 'CREATE_ENTRY_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SELECTED_ENTRY = 'SELECTED_ENTRY';
